"""Grafana dashboard JSON exporter.

Generates a Grafana dashboard JSON template from SLO calculation results
that can be imported via the Grafana API or UI as a starting point.

NOTE: This produces a static snapshot dashboard — it displays the SLO values
at the time of export. For live dashboards connected to Azure Monitor, use
this as a structural template and connect your own Azure Monitor or
Azure Data Explorer data source in Grafana.
"""

import json
from datetime import datetime, timezone
from typing import Any, Dict, List

from azure_slo_guardian.slo_calculator import SLOStatus


def export_grafana_dashboard(
    results: List[SLOStatus],
    title: str = "SLO Dashboard",
    uid: str = "slo-guardian",
) -> Dict[str, Any]:
    """Build a Grafana dashboard JSON model from SLO results.

    The generated dashboard uses stat and gauge panels to display
    current SLI values, error budget remaining, and SLO target lines.

    Args:
        results: List of SLOStatus objects.
        title: Dashboard title.
        uid: Dashboard UID for idempotent imports.

    Returns:
        Grafana dashboard JSON dictionary ready for import.
    """
    panels: List[Dict[str, Any]] = []
    y_pos = 0

    for idx, r in enumerate(results):
        budget_remaining = 100.0 - r.error_budget.error_budget_consumed_pct

        # -- SLI stat panel ------------------------------------------------
        panels.append(
            _stat_panel(
                panel_id=idx * 3 + 1,
                title=f"{r.slo_name} — SLI",
                value=r.current_sli,
                unit="percent",
                thresholds=[
                    {"color": "red", "value": None},
                    {"color": "orange", "value": r.objective.target - 0.5},
                    {"color": "green", "value": r.objective.target},
                ],
                grid_pos={"h": 4, "w": 8, "x": 0, "y": y_pos},
            )
        )

        # -- Budget gauge panel --------------------------------------------
        panels.append(
            _gauge_panel(
                panel_id=idx * 3 + 2,
                title=f"{r.slo_name} — Budget Remaining",
                value=budget_remaining,
                unit="percent",
                max_val=100,
                thresholds=[
                    {"color": "red", "value": None},
                    {"color": "orange", "value": 10},
                    {"color": "green", "value": 25},
                ],
                grid_pos={"h": 4, "w": 8, "x": 8, "y": y_pos},
            )
        )

        # -- Status text panel ---------------------------------------------
        status_text = "PASS" if r.is_meeting_slo else "FAIL"
        panels.append(
            _stat_panel(
                panel_id=idx * 3 + 3,
                title=f"{r.slo_name} — Status",
                value=1.0 if r.is_meeting_slo else 0.0,
                unit="short",
                thresholds=[
                    {"color": "red", "value": None},
                    {"color": "green", "value": 1},
                ],
                grid_pos={"h": 4, "w": 8, "x": 16, "y": y_pos},
                override_display=status_text,
            )
        )

        y_pos += 4

    now = datetime.now(timezone.utc).isoformat()

    dashboard: Dict[str, Any] = {
        "dashboard": {
            "uid": uid,
            "title": title,
            "tags": ["slo", "slo-guardian", "auto-generated"],
            "timezone": "utc",
            "schemaVersion": 39,
            "version": 1,
            "refresh": "5m",
            "time": {"from": "now-30d", "to": "now"},
            "annotations": {"list": []},
            "panels": panels,
        },
        "overwrite": True,
        "message": f"Auto-generated by Azure SLO Guardian at {now}",
    }
    return dashboard


def export_grafana_json(
    results: List[SLOStatus],
    title: str = "SLO Dashboard",
    uid: str = "slo-guardian",
    indent: int = 2,
) -> str:
    """Return the Grafana dashboard as a JSON string."""
    return json.dumps(
        export_grafana_dashboard(results, title=title, uid=uid),
        indent=indent,
    )


# ---------------------------------------------------------------------------
# Panel helpers
# ---------------------------------------------------------------------------


def _stat_panel(
    panel_id: int,
    title: str,
    value: float,
    unit: str,
    thresholds: List[Dict],
    grid_pos: Dict[str, int],
    override_display: str | None = None,
) -> Dict[str, Any]:
    panel: Dict[str, Any] = {
        "id": panel_id,
        "type": "stat",
        "title": title,
        "gridPos": grid_pos,
        "fieldConfig": {
            "defaults": {
                "unit": unit,
                "thresholds": {
                    "mode": "absolute",
                    "steps": thresholds,
                },
            },
        },
        "options": {
            "reduceOptions": {"calcs": ["lastNotNull"]},
            "colorMode": "background",
        },
        "targets": [
            {
                "refId": "A",
                "datasource": {"type": "static", "uid": "-- Mixed --"},
                "rawSql": "",
            }
        ],
        "_slo_guardian_value": value,
    }
    if override_display:
        panel["options"]["text"] = {"valueSize": 32}
        panel["_slo_guardian_display"] = override_display
    return panel


def _gauge_panel(
    panel_id: int,
    title: str,
    value: float,
    unit: str,
    max_val: float,
    thresholds: List[Dict],
    grid_pos: Dict[str, int],
) -> Dict[str, Any]:
    return {
        "id": panel_id,
        "type": "gauge",
        "title": title,
        "gridPos": grid_pos,
        "fieldConfig": {
            "defaults": {
                "unit": unit,
                "min": 0,
                "max": max_val,
                "thresholds": {
                    "mode": "absolute",
                    "steps": thresholds,
                },
            },
        },
        "options": {
            "reduceOptions": {"calcs": ["lastNotNull"]},
            "showThresholdLabels": False,
            "showThresholdMarkers": True,
        },
        "targets": [
            {
                "refId": "A",
                "datasource": {"type": "static", "uid": "-- Mixed --"},
                "rawSql": "",
            }
        ],
        "_slo_guardian_value": value,
    }
